-- Task 1.1
USE shop;

DROP TABLE IF EXISTS logs;

CREATE TABLE logs(
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	table_name VARCHAR(255) NOT NULL,
	primary_id INT UNSIGNED NOT NULL, 
	name_content VARCHAR(255) 
) COMMENT = 'log file' ENGINE=archive;

DELIMITER //

DROP TRIGGER IF EXISTS users_log//

CREATE TRIGGER users_log AFTER INSERT ON users FOR EACH ROW
BEGIN
	INSERT INTO logs VALUES
	(DEFAULT, 'users', NEW.id, NEW.name);
END; //

DROP TRIGGER IF EXISTS catalogs_log//

CREATE TRIGGER catalogs_log AFTER INSERT ON catalogs FOR EACH ROW
BEGIN
	INSERT INTO logs VALUES
	(DEFAULT, 'catalogs', NEW.id, NEW.name);
END; //

DROP TRIGGER IF EXISTS products_log//

CREATE TRIGGER products_log AFTER INSERT ON products FOR EACH ROW
BEGIN
	INSERT INTO logs VALUES
	(DEFAULT, 'products', NEW.id, NEW.name);
END; //

DELIMITER ;

-- Task 1.2
TRUNCATE users;

INSERT INTO users 
  (id, name)
SELECT 
  n, CONCAT('User', n) 
FROM
  (
  SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + e.N * 10000 + f.N * 100000 + 1 N
  FROM (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
        , (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
        , (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
        , (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
        , (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
        , (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) f
  ) t;
 
SELECT COUNT(*) AS total FROM users;





