CREATE DATABASE IF NOT EXISTS vk;

USE vk;

CREATE TABLE IF NOT EXISTS photo_albums(
	id SERIAL PRIMARY KEY,
	name VARCHAR(150) NOT NULL,
	description VARCHAR(255),
	user_id BIGINT UNSIGNED NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX (name),
	FOREIGN KEY (user_id) REFERENCES users (id)
);

INSERT INTO photo_albums VALUES (DEFAULT, 'My photo', 'Photo from vacation', 1, DEFAULT, DEFAULT);

SELECT * FROM photo_albums;

CREATE TABLE IF NOT EXISTS likes(
	user_id BIGINT UNSIGNED NOT NULL,
	media_id BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (user_id, media_id),
	FOREIGN KEY (user_id) REFERENCES users (id),
	FOREIGN KEY (media_id) REFERENCES media (id)
);

INSERT INTO likes VALUES (1, 2);

SELECT * FROM likes;

CREATE TABLE IF NOT EXISTS posts(
	id SERIAL PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL,
	post TEXT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users (id)
);

INSERT INTO posts VALUES (DEFAULT, 1, 'Hello, world!', DEFAULT, DEFAULT);

SELECT * FROM posts;

